# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  
name: R-CMD-check
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    uses: actions/cache@v1
    uses: actions/checkout@v2
    uses: r-lib/actions/setup-r@v1
    steps:
    - name: Cache packages
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    
    - name: Run-Unittest
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages(c("renv", "devtools"))
        renv:: init()
        renv::restore()
        devtools::test()




    
