name: test-GolemShowcase
on:
 push:
  branches:
   - dev
   - main
   - master
jobs:
 say-hello:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: r-lib/actions/setup-r@v1
   - run: Rscript --version